LittlerootTown_MapScripts::
	.byte 0


SpringwoodLake_EventScript_SpringrockPathSign::
	lockall
	msgbox SpringwoodLake_EventScript_SpringrockPathSign_Text_0
	releaseall
	return


SpringwoodLake_EventScript_PlayersHouse::
	lockall
	msgbox SpringwoodLake_EventScript_PlayersHouse_Text_0
	releaseall
	return


SpringwoodLake_EventScript_SpringwoodLakeSign::
	lockall
	msgbox SpringwoodLake_EventScript_SpringwoodLakeSign_Text_0
	releaseall
	return


SpringwoodLake_EventScript_BellasHouse::
	lockall
	msgbox SpringwoodLake_EventScript_BellasHouse_Text_0
	releaseall
	return


SpringwoodLake_EventScript_SakurasHouse::
	lockall
	msgbox SpringwoodLake_EventScript_SakurasHouse_Text_0
	releaseall
	return


SpringwoodLake_EventScript_SakurasLab::
	lockall
	msgbox SpringwoodLake_EventScript_SakurasLab_Text_0
	releaseall
	return


SpringwoodLake_EventScript_SpringrockPathSign_Text_0:
	.string "Springrock Path$"

SpringwoodLake_EventScript_PlayersHouse_Text_0:
	.string "{PLAYER}'s House$"

SpringwoodLake_EventScript_SpringwoodLakeSign_Text_0:
	.string "Springwood Lake\p"
	.string "Home of the famous Professor Sakura\n"
	.string "and her Research Institute!$"

SpringwoodLake_EventScript_BellasHouse_Text_0:
	.string "Bella's House$"

SpringwoodLake_EventScript_SakurasHouse_Text_0:
	.string "Sakura's House$"

SpringwoodLake_EventScript_SakurasLab_Text_0:
	.string "Professor Sakura's Research Institute\p"
	.string "Accredited research facility for\n"
	.string "Pokémon science and technology$"
